name = "chiakeo"
main = "worker/src/index.ts"
compatibility_date = "2026-07-03"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "chiakeo-db"
database_id = "d583fc77-ae15-4dfc-9c23-e36240e437f3"
migrations_dir = "drizzle"

[vars]
ALLOWED_ORIGINS = ""
